### ISSUE TITLE
Release version 0.0.3?

### ISSUE THREAD

**Issue by AdrianGaudebert** [elasticsearch/elasticsearch-dsl-py#41]
Hello, 

I need to use the ``match_phrase`` query and it is not included in the current version on pypi, 0.0.2. Would it be possible to cut a release so that newest features are made available? Or is there another way to access that feature without waiting for a release? 

Cheers,
Adrian

**Comment by Schwankenson** [comment]
I would like to use the DocType / Mapping feature. When will the new version be available? Would be a great thing to work with it...

**Comment by m-vdb** [comment]
@HonzaKral I also need the release, partly because of match_phrase (which we agree is just a shortcut). If you need any help with something let me know. I've been digging into your code in the past weeks so I know a bit of it :)

**Comment by HonzaKral** [comment]
Currently I am working on documentation, I hope to cut a release by the end of the week, thanks for your patience.

**Comment by m-vdb** [comment]
thanks! good luck

**Comment by HonzaKral** [comment]
Done - https://pypi.python.org/pypi/elasticsearch-dsl 

Thanks for your patience!

**Comment by m-vdb** [comment]
So cool!
