### ISSUE TITLE
Can't import anything from elasticsearch_dsl

### ISSUE THREAD

**Issue by iodbh** [elasticsearch/elasticsearch-dsl-py#53]
Hello,

I can't seem to run the Peristance Example from the documentation : I can't import anything from py_elasticsearch.

Here is a REPL example session :

Python 3.4.0 (v3.4.0:04f714765c13, Mar 15 2014, 23:02:41) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
    >>> from datetime import datetime
    >>> from elasticsearch import Elasticsearch
    >>> from elasticsearch_dsl import DocType, String, Date, Integer, connections
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    ImportError: cannot import name 'DocType'
    >>> import elasticsearch_dsl
    >>> dir(elasticsearch_dsl)
    ['A', 'F', 'Q', 'SF', 'Search', 'VERSION', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '__versionstr__', 'aggs', 'exceptions', 'filter', 'function', 'query', 'result', 'search', 'utils']
    >>> elasticsearch_dsl.__version__
    (0, 0, 2)
    >>>

Python version 3.4.0 on Mac OS X (Yosemite), Python 3.4.0
I installed the module with :
pip3 install elasticsearch_py

I have the same problem when using python 2 (Mac OS's stock interpreter)

**Comment by HonzaKral** [comment]
I am sorry, this is my fault - I forgot to increment the version in master after doing the `0.0.2` release. The `DocType` functionality is only in the unreleased version on github. I should do a `0.0.3` release soon that will contain it and will make sure I get the versioning right this time.

In the mean time I am afraid you have to install the dsl directly from github if you wish to use the persistence features.

**Comment by iodbh** [comment]
I confirm that everything worked properly after reinstalling from github. Thank you for your work and your help !
