### ISSUE TITLE
Add support for adding highlighting to a `Search` object

### ISSUE THREAD

**Issue by robhudson** [elasticsearch/elasticsearch-dsl-py#57]
http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-highlighting.html

**Comment by robhudson** [comment]
Woo. Thanks! That was fast.

**Comment by robhudson** [comment]
I wonder if instead of taking a single field and `**kwargs` it could take `*args`, each one being a field to highlight if there's more than one? e.g. `Search().highlight('title', 'body')`? Otherwise you have to do `Search().highlight('title').highlight('body')` which seems a little awkward.

**Comment by HonzaKral** [comment]
and if you supplied kwargs would it then be applied to all the fields? Makes sense...

**Comment by robhudson** [comment]
I suppose, yes, all fields. If you needed different kwargs for different fields you can call it multiple times?

**Comment by HonzaKral** [comment]
Exactly, as implemented in 59b2662
