### ISSUE TITLE
syntax error when passing special fields as keyword arguments

### ISSUE THREAD

**Issue by theNewFlesh** [elasticsearch/elasticsearch-dsl-py#59]
Fields such as '@timestamp' and '@version' (ones essential to Logstash) cannot be passed as keyword arguments to methods such as query and filter because the @ signed causes Python to throw a syntax error.  These are needed in creating time range filters and queries.  Perhaps making a special keyword arg called '__parent',  which resolves to a key under which the other kwargs are nested would do the trick.  So, for instance I invoke:
```
s = Search(using=es) \
.filter('range', __parent='@timestamp', gte='now-5m', lte='now')
s.to_dict()
```
and get
```
...
'filter': {
    'range': {
        '@timestamp': {
            'gte': 'now-5m',
            'lte': 'now'
...
```

**Comment by HonzaKral** [comment]
What you can do in this case is just specify `**{'@timestamp': {"gte": "now-5m", "lte": "now"}}` which should just work. I will add a note to the documentation.
