### ISSUE TITLE
DocType doesn't work as expected with Search.

### ISSUE THREAD

**Issue by assumptionsoup** [elasticsearch/elasticsearch-dsl-py#60]
The [persistence doc](https://github.com/elasticsearch/elasticsearch-dsl-py/blob/master/docs/persistence.rst) suggests that the following should work:
```
from elasticsearch_dsl import DocType, Search

class MyDoc(DocType):
    pass

s = Search(index='my_index')
s = s.doc_type(MyDoc)
s.execute()
```
But this results in a TypeError (using elasticsearch-py 1.2.0 and elasticsearch-dsl-py latest commit 60a1123a36674afc274508d5beaf56774112a81b):
```
elasticsearch/client/utils.pyc in _escape(value)
     16     # make sequences into comma-separated stings
     17     if isinstance(value, (list, tuple)):
---> 18         value = ','.join(value)
     19
     20     # dates and datetimes into isoformat

TypeError: sequence item 0: expected string or Unicode, DocTypeMeta found
```
Additionally, DocType.search doesn't take "index" or "using" parameters, so if I have an explicit index, I can't simply do:
```
s = MyDoc.search(index='my_index', using='custom_alias')
```

**Comment by HonzaKral** [comment]
You are absolutely correct, this is my fault where I have the documentation wrong. For the time being the way to do this is by specifying:

    s = Search(index='my_index')
    s = s.doc_type(my_doc=MyDoc.from_es)
    s.execute()

This is obviously not ideal so I will be working on providing a more convenient way.

Sorry for the confusion.

**Comment by assumptionsoup** [comment]
Thanks for the quick reply!  When you work on a more convenient way, please consider that
`s.doc_type(my_doc=MyDoc.from_es)` hardcodes the doc type of `MyDoc`, which is already encapsulated in `MyDoc`.  I've been using `s = s.doc_type(**{MyDoc._doc_type.name: MyDoc.from_es})` to get around this, but I don't like that I have to use a protected attribute.

**Comment by assumptionsoup** [comment]
I just started using elasticsearch-dsl, so I may just be missing a more obvious way to get a string doc_type from a `DocType` class.

**Comment by HonzaKral** [comment]
yep, definitely the reason why I still want a more convenient way. This way is essentially just a hack or hook for people wanting to do their own wrapping so they can hook in their callback.

And no, there is no better way to get it out, you found the correct one.

**Comment by assumptionsoup** [comment]
Cool, thanks.
