### ISSUE TITLE
How to set source filtering in query?

### ISSUE THREAD

**Issue by knoguchi** [elasticsearch/elasticsearch-dsl-py#63]
I would like to set the [source filter](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-request-source-filtering.html).  Is this feature supported by the DSL?  If not, would you add this?

**Comment by HonzaKral** [comment]
Currently it is not supported directly. You can, however, use the `extra` method:

    s = Search()
    s.extra(_source={'include': ['title', 'body']})

I am not sure this is super useful to add as a separate method since it can be done this easily, but if more people request it I will add it.

Hope this helps.

**Comment by knoguchi** [comment]
Thanks for the answer.  I will use .extra().
