### ISSUE TITLE
Distribute with pypi?

### ISSUE THREAD

**Issue by kutenai** [elasticsearch/elasticsearch-dsl-py#64]
Is this package available in pyi? I tried pip install elasticsearch-dsl-py, but no luck.

**Comment by willkg** [comment]
The package is called `elasticsearch-dsl`:

```
pip install elasticsearch-dsl
```

https://pypi.python.org/pypi/elasticsearch-dsl

**Comment by HonzaKral** [comment]
Yes, as Will said. The version installable from PYPI is not 100% up to date, I will do another release soon once we hammer out the details regarding #58 and attribute access to fields in `_meta`.
