### ISSUE TITLE
term filter not working with string field

### ISSUE THREAD

**Issue by leoaguirre32** [elasticsearch/elasticsearch-dsl-py#65]
I'm trying to run a match query and a term filter with elasticsearch-dsl.
When I run Search(es, index='haystack').query("match", _all=q) the results return as expected. But when I add a filter Search(es, index='haystack').query("match", _all=q).filter('term', tipo_anuncio='Aluguel'), the response is empty, when I expected to be the first item of the list bellow.

When I apply the same filter but with a numeric variable, for example Search(es, index='haystack').query("match", _all=q).filter('term', num_banheiros=4) the filter works. What am I doing wrong?

This is a part of my script in Django:

q = request.GET.get('q', '')
es = Elasticsearch()
s = Search(es, index='haystack').query("match", _all=q).filter('term', tipo_anuncio='Aluguel')
results = s.execute()

This is my result when I run the search without the filter:

{
    "took": 2,
    "timed_out": false,
    "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
    },
    "hits": {
        "total": 2,
        "max_score": 0.97323877,
        "hits": [
            {
                "_index": "haystack",
                "_type": "modelresult",
                "_id": "anunciar.anunciarimovel.2",
                "_score": 0.97323877,
                "_source": {
                    "area_util": "600",
                    "tipo_anuncio": "Aluguel",
                    "num_banheiros": "4"
                }
            },
            {
                "_index": "haystack",
                "_type": "modelresult",
                "_id": "anunciar.anunciarimovel.7",
                "_score": 0.97323877,
                "_source": {
                    "area_util": "380",
                    "tipo_anuncio": "Venda",
                    "num_banheiros": "3"
                }
            }
        ]
    }
}

Thanks!

**Comment by HonzaKral** [comment]
This is impossible to answer without knowing what mappings you have.

My guess is that the field you are trying to filter on is analyzed, which means that the value indexed is not actually `Aluguel` but a normalized version of that - lowercased and possibly stemmed.

To fix this you need to change your mapping to have this field as `"index": "not_analyzed"`. If you also want it for search then you can use the multi-field capabilities to have two different configurations for the same field.

Hope this helps.

**Comment by apandita** [comment]
Just to add on  Honza's answer, One way you can try and see if its ur field
that is analysed is to try run a query instead of a filter.
Queries run on analysed fields .
With this you will know right away if its the mapping that you need to
alter.

Cheers
Amit

**Comment by leoaguirre32** [comment]
thank you very much @HonzaKral  and @apandita , you were wright! solved it!

I'm closing the issue.

Cheers!

**Comment by ranvijay-sachan** [comment]
Hi i am trying to apply filter on string field and its not working. Please take a look: 
http://stackoverflow.com/questions/44096694/elasticsearch-dsl-term-filter-not-working-with-string-field

Thanks.
