### ISSUE TITLE
Documentation example of overriding save method does not work under Python 2.7.6

### ISSUE THREAD

**Issue by douglascamata** [elasticsearch/elasticsearch-dsl-py#69]
```python
    return super().save(**kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by zivori** [comment]
super() (without arguments) was introduced in python3
[http://stackoverflow.com/questions/10482953/python-extending-with-using-super-python-3-vs-python-2]

**Comment by douglascamata** [comment]
And the Python 2 way of doing it, like `super(DocType, self).save(**kwargs)` doesn't work. Says the super doesn't have the `save` method.
