### ISSUE TITLE
"found" field added after MyDocType.get(): expected behaviour?

### ISSUE THREAD

**Issue by njoannin** [elasticsearch/elasticsearch-dsl-py#70]
I've been playing around with the persistance example.
I just noticed that after I use the get method, there is a "found" field added to my document.
Saving, then adds that field to the document, and obviously to the mapping.

Is this the expected behaviour?

**Comment by HonzaKral** [comment]
This is not an expected behavior, thanks for the report, I will fix it.

**Comment by njoannin** [comment]
Happy to help out!

**Comment by njoannin** [comment]
Honza, I have been working with the latest stable version (0.0.3). That is where I saw the bug.
After you assigned yourself the bug, I went and downloaded the latest dev version (0.0.4).
I just tested it now, but the issue does not seem to occur.

So this seems to be a non existing bug in the dev version, although present in the current stable release.

**Comment by HonzaKral** [comment]
Ah cool. Yeah - we changed the behavior of that part so I wondered if it would still be an issue. Thanks for checking and coming back with the results.

I am closing this ticket as it has been resolved on master. I will release a new version soon to distribute the fix.
