### ISSUE TITLE
Sort of result cache?

### ISSUE THREAD

**Issue by douglascamata** [elasticsearch/elasticsearch-dsl-py#74]
A have these simple tests: 

```python
    def setUp(self):
        connections.add_connection('default', Elasticsearch())
        Report.init()

    def tearDown(self):
        for item in Report.search().execute():
            item.delete()

    def test_report_creation(self):
        report = Report(description='My very first report')
        report.save()
        self.assertEqual(report.description, 'My very first report')
        self.assertEqual(len(Report.search().execute().hits), 1)

    def test_elastic_search_model_dict(self):
        report = Report(description='Test as dict')
        result = report.to_dict()
        self.assertEqual(result['description'], 'Test as dict')
```

But my teardown is failing with `elasticsearch.exceptions.NotFoundError: TransportError(404, '{"found":false,"_index":"report","_type":"report","_id":"AUuYRTKebDsWwG82cPzd","_version":3}')`

Seems like my search is returning something that isn't in ES yet. Any ideas?

**Comment by HonzaKral** [comment]
Your search is returning documents deleted by teardown. This is because you
don't call refresh after save/delete. This you typically don't want to do
in production but it's crucial in tests.

Hope this helps

**Comment by douglascamata** [comment]
I just tried putting `Report._doc_type.refresh()` in all the possible places and it didn't work. Can you give me a light here, please?

**Comment by HonzaKral** [comment]
You need to call refresh at every `.save` and `.delete` you are calling from your tests, easiest way is to just pass `refresh=True` to the calls.

Also I would recommend just deleting the index in your `tearDown` method. So overall your tests should look like:

    def setUp(self):
        connections.add_connection('default', Elasticsearch())
        Report.init()

    def tearDown(self):
        connections.get_connection.indices.delete(index='my-test-index')

    def test_report_creation(self):
        report = Report(description='My very first report')
        report.save(refresh=True)
        self.assertEqual(report.description, 'My very first report')
        self.assertEqual(len(Report.search().execute().hits), 1)

    def test_elastic_search_model_dict(self):
        report = Report(description='Test as dict')
        result = report.to_dict()
        self.assertEqual(result['description'], 'Test as dict')

**Comment by douglascamata** [comment]
Thanks!
