### ISSUE TITLE
DocType Date field is timezone naive

### ISSUE THREAD

**Issue by jxstanford** [elasticsearch/elasticsearch-dsl-py#77]
It appears that any document stored with an ISO8601 date will be tzlocal, regardless of the stored timezone, when retrieved.  There are a couple possible solutions, and I'm willing to make a pull request if one of them is acceptable:

http://crsmithdev.com/arrow/ -- I use this quite a bit, and like it
https://pypi.python.org/pypi/iso8601/ -- I haven't used this, but it seems sufficient

**Comment by HonzaKral** [comment]
I see different results - in d83d49e6987ad413f1ae08dc8044f702cc4b2e90 you can see that a datetime created with a timezone information comes back as timezone-aware. Is there something I am missing?

Thanks!

**Comment by jxstanford** [comment]
My apologies.  I reviewed my integration test, and think I may have had a mapping or some other problem.  


John

jxstanford@gmail.com
@jxstanford

**Comment by HonzaKral** [comment]
Closing the issue then, thanks
