### ISSUE TITLE
percentile_rank aggregation should be percentile_ranks

### ISSUE THREAD

**Issue by frecklesarus** [elasticsearch/elasticsearch-dsl-py#78]
Hi, 

Working on some aggregations and came across this simple bug. In aggs, the percentile_ranks aggregation is listed as 'percentile_rank'.  It should be 'percentile_ranks'.  

ie)
s.aggs['per_tag'].bucket('load_percent', 'percentile_ranks', field='load_time', values=[120])

returns this error:
elasticsearch_dsl.exceptions.UnknownDslObject: DSL class percentile_ranks does not exist in agg.

Using 'percentile_rank': 
s.aggs['per_tag'].bucket('load_percent', 'percentile_rank', field='load_time', values=[15])

returns  a Parse Failure from Elasticsearch

Thanks!

**Comment by NorthStar** [comment]
True. It is just a typo. I'll send a quick pr.
