### ISSUE TITLE
analyzer="path_hierarchy" not recognized?

### ISSUE THREAD

**Issue by njoannin** [elasticsearch/elasticsearch-dsl-py#82]
Setting a field to:

```
path = String(analyzer="path_hierarchy")
```

... causes the following error:

```
elasticsearch.exceptions.RequestError: TransportError(400, 'MapperParsingException[Analyzer [path_hierarchy] not found for field [path]]')
```

I'm wondering why it recognizes ```analyzer="snowball"``` (as in the persistance example) but not ```analyzer="path_hierarchy"```?

**Comment by njoannin** [comment]
Ok, just figured it out: ```snowball``` is an ```analyzer``` ([link] (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-analyzers.html)) whereas ```path_hierarchy``` is a ```tokenizer``` ([link] (http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-tokenizers.html)).

And, there doesn't seem to be a "path" analyzer :(

Sorry for the non-issue.

**Comment by HonzaKral** [comment]
No worries, I want to have support for `Analyzer` objects in the future - allowing you to define them in python using another mini dsl. In the mean time, however, you need to define them manually and use their string names.

**Comment by njoannin** [comment]
That'd be cool!
