### ISSUE TITLE
Bool query can not support minimum_number_should_match field

### ISSUE THREAD

**Issue by JiounDai** [elasticsearch/elasticsearch-dsl-py#87]
Bool query can not support minimum_number_should_match field , i.e 
"bool":{
      "must":[
        {
          "match":{
            "status":"success"
          }
        }
      ],
      "should":[
        {
          "term":{"eventid":4771}
        },
        {
          "term":{"eventid":4768}
        }
      ],
      "minimum_should_match" : 1
    }

**Comment by JiounDai** [comment]
I can not add  "minimum_should_match" : 1 in query

**Comment by HonzaKral** [comment]
You should be able to create a query like this via:

    s = Search().query(
        'bool',
        should=[Q('term', enventid=4771), Q('term', eventid=4768)],
        must=[Q('match', status='success')],
        minimum_should_match=1
    )

Alternatively you can do:
  
    s = Search().query('match', status='success')
    s = s.query(Q('term', enventid=4771) | Q('term', eventid=4768))
    s.query.minimum_should_match = 1


Note however that for your query it is much better to use a `terms` filter:

    s = Search().query('match', status='success').filter('terms', eventid=[4771, 4768])

Hope this helps.

**Comment by JiounDai** [comment]
OK, thank you!

**Comment by HonzaKral** [comment]
Glad I could help.
