### ISSUE TITLE
Problem with .query() (using match with field) and Match

### ISSUE THREAD

**Issue by goodrichj** [elasticsearch/elasticsearch-dsl-py#91]
I'm having a lot of trouble with what the docs describe here:
http://elasticsearch-dsl.readthedocs.org/en/latest/search_dsl.html#queries

```python
from elasticsearch_dsl import Match
```
Match doesn't import for me.

```python
s = s.query('match', query='python django', field='title', operator='or')
```
I get an error trying to execute anything using this pattern:

query('match', query='something', field='somefield')

**Comment by HonzaKral** [comment]
I am sorry, the documentation is wrong, it should be:

    query('match', somefield={'query': 'something', 'operator': 'or'})

it always copies very closely the json dsl. Will push a fix to the docs asap.
