### ISSUE TITLE
Upsert a document using .save or implement .update method

### ISSUE THREAD

**Issue by rochacbruno** [elasticsearch/elasticsearch-dsl-py#93]
Hi, 

Right now I am using 

```python
    def index_via_requests(doc_type, body, doc_id, index_name=None):
        url = 'http://localhost:9200/{index_name}/{dtype}/{did}'.format(
            index_name=index_name, dtype=doc_type, did=doc_id,
        )
        data=json.dumps(body)
        response = requests.put(url, data=data)
        return response
```

With the above method I can perform upserts, if the document with specified ID already exists it is updated, otherwise it is created.

I've tried.

```python

class Animal(DocType):
    name = String()
    location = String()

    class Meta:
        index = "my_index"
        doc_type="animal"

```

And then

```python

Animal(name="Quokka", location="Australia", _id=1234).save(using=my_connection)

```

The above works for the first time, it returns True if the _id=1234 does not exists, but if the document already exists it returns False.

How can I perform an upsert?

```python

Animal(name="Quokka", location="Australia", _id=1234).update(using=my_connection)

```

or

```python

Animal(name="Quokka", location="Australia", _id=1234).save(using=my_connection, upsert=True)

```

Thanks

**Comment by HonzaKral** [comment]
The return `False` just means that the document has been updated and not created. Sorry if that is confusing, will update the docs to be clearer.

**Comment by rochacbruno** [comment]
@HonzaKral thanks for your quick answer!

Understood!!
